# Generated by Django 2.0.2 on 2018-02-07 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_admin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tooltip', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.DecimalField(decimal_places=0, help_text='Order relative to its parent', max_digits=2, null=True)),
                ('global_order', models.DecimalField(decimal_places=0, max_digits=40, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.MenuItem')),
            ],
        ),
    ]
