# Generated by Django 2.0.2 on 2018-02-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20180207_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.IntegerField(default=-1, help_text='Order relative to its parent'),
            preserve_default=False,
        ),
    ]
