# Generated by Django 2.0.2 on 2018-02-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20180206_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.MenuItem')),
                ('global_order', models.DecimalField(decimal_places=0, max_digits=40)),
            ],
            bases=('menu.menuitem',),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.DecimalField(decimal_places=0, default=-1, help_text='Order relative to its parent', max_digits=2),
            preserve_default=False,
        ),
    ]
