# Generated by Django 2.0.2 on 2018-02-06 16:03

from django.db import migrations
from django.conf import settings

def create_admin(apps, se):
    if not settings.DEBUG:
        return
    User = apps.get_model('auth', 'User')
    User.objects.create(username='admin', password='admin', is_staff=True)

class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20180206_1552'),
    ]

    operations = [
        migrations.RunPython(create_admin)
    ]
