# Generated by Django 2.0.2 on 2018-02-06 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20180206_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_order', models.DecimalField(decimal_places=0, max_digits=40)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.MenuItem')),
            ],
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='menuitem_ptr',
        ),
        migrations.DeleteModel(
            name='OrderedItem',
        ),
    ]
